// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package segments

import (
	"database/sql"
)

type Segment struct {
	ID          string
	LectureID   string
	Tags        []string
	Prev        string
	Next        string
	Content     string
	Voice       string
	Script      string
	StructureID string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type SegmentsLocal struct {
	ID          string
	LectureID   string
	Tags        []string
	Prev        string
	Next        string
	Content     string
	Voice       string
	Script      string
	StructureID string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}
