// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user_subjects

import (
	"database/sql"
)

type UserSubject struct {
	ID        string
	UserID    string
	SubjectID string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
