// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package chats

import (
	"database/sql"
)

type Chat struct {
	ID        string
	UserID    string
	SegmentID string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
