openapi: 3.0.0
info:
  title: Progress Management API
  version: 1.0.0

paths:
  /progress:
    post:
      summary: Register progress for a lecture
      operationId: registerProgress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lecture_id:
                  type: string
                  description: ID of the lecture
                user_id:
                  type: string
                  description: ID of the user
      responses:
        '200':
          description: Progress registered successfully
        '400':
          description: Invalid input data
        '500':
          description: Internal server error

  /progress/{user_id}:
    get:
      summary: Display progress for ongoing courses
      operationId: displayOngoingProgress
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            description: ID of the user
      responses:
        '200':
          description: Progress retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    lecture_id:
                      type: string
                    name:
                      type: string
                    ratio:
                      type: number
                      format: float
        '400':
          description: Invalid user ID
        '500':
          description: Internal server error

  /progress/{user_id}/{month}:
    get:
      summary: Calculate and return the learning volume for the month
      operationId: getMonthlyLearningVolume
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            description: ID of the user
        - name: month
          in: path
          required: true
          schema:
            type: string
            description: Month in format 'YYYY-MM'
      responses:
        '200':
          description: Monthly learning volume retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  lectures:
                    type: integer
                    description: Number of lectures completed
                  courses:
                    type: integer
                    description: Number of courses completed
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        course_name:
                          type: string
                        lecture_name:
                          type: string
                        created_at:
                          type: string
                          format: date-time
        '400':
          description: Invalid user ID or month format
        '500':
          description: Internal server error
