openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0

paths:
  /test/{lecture_id}:
    get:
      summary: Get quiz for a lecture
      operationId: getQuizByLectureID
      parameters:
        - name: lecture_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    text:
                      type: string
                    choices:
                      type: array
                      items:
                        type: object
                        properties:
                          text:
                            type: string
                          is_correct:
                            type: boolean
        '400':
          description: Invalid lecture ID
        '500':
          description: Internal server error
  /test/submit:
    post:
      summary: Submit quiz result
      operationId: PostQuizResult
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: string
                  test_id:
                    type: string
                  question_id:
                    type: string
                  choice_id:
                    type: string
      responses:
        '200':
          description: Quiz results submitted successfully
        '400':
          description: Invalid input data
        '500':
          description: Internal server error

      