// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user_progresses

import (
	"database/sql"
)

type UserProgress struct {
	ID        string
	LectureID string
	UserID    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
