// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package subjects

import (
	"database/sql"
)

type Subject struct {
	ID        string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
