name: fair_edu_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  intl: 0.19.0
  collection: 1.18.0
  google_fonts: 6.2.1
  form_field_validator: 1.1.0
  gap: 3.0.1
  phone_numbers_parser: 9.0.1
  intersperse: 2.0.0
  loading_animation_widget: 1.3.0
  time_machine: 0.9.17
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  riverpod_annotation: 2.3.5
  image_picker: 1.1.2
  path_provider: 2.1.4
  flutter_svg: 2.0.10
  logger: 2.4.0
  flutter_chat_ui: 1.6.15
  cupertino_icons: ^1.0.8
  drift: ^2.21.0
  uuid: 4.5.1
  faker: 2.2.0
  webview_flutter: ^4.0.6
  xml: ^6.1.0
  webview_flutter_wkwebview: ^3.16.0

  # Riverpod
  hooks_riverpod: 2.5.2
  flutter_hooks: 0.20.5

  # Navigation
  go_router: 14.2.6
  phosphor_flutter: ^2.1.0
  recase: 4.1.0

  # Local packages
  fairedu_client:
    path: packages/fairedu-client

  # Git dependencies
  scribble:
    git:
      url: git@github.com:doss-eeic/2024-07-scribble.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: 4.0.0
  custom_lint: 0.6.5
  riverpod_lint: 2.3.13

  # Code Generation
  build_runner: 2.4.12
  envied_generator: 0.5.4
  freezed: 2.5.7
  json_serializable: 6.8.0
  riverpod_generator: 2.4.3
  go_router_builder: 2.7.1

  # Icons
  flutter_launcher_icons: 0.13.1

  # Assets
  flutter_gen_runner: 5.6.0

flutter:
  uses-material-design: true
  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
