// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tests

import (
	"database/sql"
)

type Choice struct {
	ID         string
	QuestionID string
	Text       string
	IsCorrect  bool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type Question struct {
	ID        string
	TestID    string
	Text      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type QuizResult struct {
	ID         string
	TestID     string
	QuestionID string
	ChoiceID   string
	UserID     string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type Test struct {
	ID        string
	LectureID string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
